version: '3.8'

services:
  postgres:
    container_name: order-service-postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      POSTGRES_DB: order_service
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      # Initialize the database with a script
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql